#开发环境
debug: true
profiles:
  active: dev
logging:
  level:
    root: info
file: e/rizhi.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 111111
mail:
  config:
    name: 爱美商城
    description: 这是一家化妆品特卖网站
    hot-sales: 20
    show-advert: true

